name: Sync Fork

on:
  schedule:
    - cron: '0 19 1 * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: kubernetes
          base: master
          head: master
